---
- name: Check if OS is Ubuntu LTS
  fail: msg="Server must be Ubuntu LTS"
  when: ansible_distribution != 'Ubuntu'
    or (ansible_distribution_version != '14.04'
      and ansible_distribution_version != '16.04'
      and ansible_distribution_version != '18.04')

- name: Install software-properties-common
  apt:
    name: software-properties-common
    update_cache: true
    state: present

- name: Apply apt config for explicitly specified MariaDB versions
  block:
  - name: Add apt key for MariaDB
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: F1656F24C74CD1D8
  - name: Add apt repo for MariaDB
    apt_repository:
      repo: deb [arch={{ mariadb_repo_deb_arch }}] {{ mariadb_mirror_proto }}://{{ mariadb_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main
      state: present
      filename: mariadb
      update_cache: true
    tags:
      - apt-repo
  when: mariadb_version != 'auto'

- name: Install MariaDB Server
  apt:
    name: mariadb-server
    state: present
    update_cache: yes
  when: client_only == false

- name: Install MariaDB client
  apt:
    name: mariadb-client
    state: present
    update_cache: yes
  when: client_only == true

- name: Install python module
  apt: name=python-mysqldb state=present
  when: ansible_os_family == 'Debian'


- name: Save mysql root password credentials to /root/.my.cnf
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600 backup=yes
  when: (
      mysql_password_changed is defined
      and mysql_password_changed is changed
    )
    or (
      client_only == true
      and mysql_root_password is defined
    )

- name: Apply Acro's MariaDB 10.0 server config to Ubuntu 16.04
  template:
    src: etc/mysql/conf.d/acro.cnf.j2
    dest: /etc/mysql/conf.d/acro.cnf
    owner: root
    mode: 0644
    backup: yes
  notify:
    - armdb restart mysql
  when: ansible_distribution_version == '16.04'
    and client_only == false

- name: Apply MariaDB server customizations on Ubuntu >= 18.04
  template:
    src: etc/mysql/mariadb.conf.d/99-acromedia-server-overrides.cnf.j2
    dest: "{{ mysql_include_dir }}/99-acromedia-server-overrides.cnf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - armdb restart mysql
  when: ansible_distribution == 'Ubuntu' and
    ansible_distribution_major_version|int >= 18
    and client_only == false

- name: Apply MariaDB cient customizations on Ubuntu >= 18.04
  template:
    src: etc/mysql/mariadb.conf.d/99-acromedia-client-overrides.cnf.j2
    dest: "{{ mysql_include_dir }}/99-acromedia-client-overrides.cnf"
    owner: root
    mode: 0644
    backup: yes
  when: ansible_distribution == 'Ubuntu' and
    ansible_distribution_major_version|int >= 18
