- name: Check if OS is Ubuntu 14.04 or 16.04
  fail: msg="Server must be Ubuntu 14.04 or 16.04"
  when: ansible_distribution != 'Ubuntu' or (ansible_distribution_version != '14.04' and ansible_distribution_version != '16.04')

- name: Install software-properties-common
  apt: name=software-properties-common update_cache=yes state=present
  
- name: Install MariaDB Server
  apt: name=mariadb-server state=present update_cache=yes
  
- name: Install python module
  apt: name=python-mysqldb state=installed

- name: Ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: Check for existence of /root/.my.cnf
  stat: path=/root/.my.cnf
  register: root_my_cnf

- name: Check if mysql root password set
  fail: msg="/root/.my.cnf must exist, or --extra-vars 'mysql_root_password=SOME_PASSWORD' must be passed in"
  when: root_my_cnf.stat.exists == False and mysql_root_password is not defined

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=$item state=absent
  with_items:
    - localhost
    - "{{ ansible_fqdn }}"

- name: remove the test database
  mysql_db: name=test state=absent

# 'localhost' needs to be the last item for idempotency, see http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password
  mysql_user: "name=root host={{ item }} password={{ mysql_root_password }}"
  with_items:
    - "{{ ansible_fqdn }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: root_my_cnf.stat.exists == False or mysql_root_password is defined
  register: mysql_password_changed

- name: copy .my.cnf file with root password credentials
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600 backup=yes
  when: mysql_password_changed|changed

- name: Apply Acro's MariaDB 10.0 server config
  template: src=etc/mysql/conf.d/acro.cnf.j2 dest=/etc/mysql/conf.d/acro.cnf owner=root mode=0644 backup=yes
  notify:
    - restart mysql
