- name: Check for existence of /root/.my.cnf
  stat: path=/root/.my.cnf
  register: root_my_cnf

- name: Fail when /root/.my.cnf doesn't exist, and no root password has been provided
  fail:
    msg: Could not read password from /root/.my.cnf. If this is the first time running your playbook, append `  --extra-vars mysql_root_password=$(openssl rand -base64 24) `  to your command line. Setting the mysql root password only needs to be done once.
  when: root_my_cnf is defined
    and root_my_cnf.stat is defined
    and root_my_cnf.stat.exists == False
    and mysql_root_password is not defined

- include_tasks: "tasks/{{ ansible_os_family }}.yml"

- include_tasks: "tasks/server-common.yml"
  when: client_only == false

- name: Save mysql root password credentials to /root/.my.cnf
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600 backup=yes
  when: (
      mysql_password_changed is defined
      and mysql_password_changed is changed
    )
    or (
      client_only == true
      and mysql_root_password is defined
    )

- include_tasks: "tasks/acro-ubuntu-config.yml"
  when: ansible_distribution == 'Ubuntu'
