- name: Bootstrap
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: robertdebock.bootstrap

- name: Prepare
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Update cache
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Ensure dirmngr is installed
      apt:
        name: dirmngr
        state: present
      when: ansible_os_family == 'Debian'
