- name: Prepare
  hosts: all
  become: true
  gather_facts: yes
  tasks:

    - name: Update yum
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Update cache
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Ensure dirmngr is installed
      apt:
        name: dirmngr
        state: present
      when: ansible_os_family == 'Debian'

