---
- name: Check mariadb is configured
  hosts: all
  become: yes

  tasks:

    - name: Create database testdb.
      command: "mysql -u root -proot  -e 'CREATE database testdb;'"


    - name: Create table testtb.
      command: "mysql -u root -proot  -e 'use testdb; CREATE TABLE testtb (id int);'"


    - name: Insert in to testtb.
      command: "mysql -u root -proot  -e 'use testdb; INSERT INTO testtb VALUES (10);'"

    - name: List the databases.
      command: "mysql -u root -proot  -e 'use testdb; SELECT * from testtb WHERE id=10;'"
      register: select
    - debug: var=select.stdout_lines
