---
- name: Check mariadb is configured
  hosts: all
  become: yes

  tasks:
    - name: Check client overrides conf has been created
      stat:
        path: /etc/mysql/mariadb.conf.d/99-acromedia-client-overrides.cnf
      register: stat_result

    - name: Make sure we can connect to MySQL via Unix socket.
      command: "mysql -u root -proot -e 'show databases;'"
      changed_when: false
