---
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - registry.gitlab.com/aussielunix/ansible/molecule-containers/ubuntu:focal # 20.04
          - registry.gitlab.com/aussielunix/ansible/molecule-containers/ubuntu:jammy # 22.04
          - registry.gitlab.com/aussielunix/ansible/molecule-containers/ubuntu:noble # 24.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Disable apparmor on the runner because of an alleged bug which
          interferes with mysql service commands. See
          https://github.com/geerlingguy/ansible-role-mysql/issues/422
        run: |
            set -x
            sudo apt-get install apparmor-profiles
            sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          image: "${{ matrix.image }}"
          options: parallel
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.image }}"
          max_failures: 1
